# Generated by Django 6.0.3 on 2026-04-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_enterprise_address_enterprise_email_enterprise_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='allowed_modules',
            field=models.JSONField(blank=True, default=list, help_text="Liste des modules autorisés (ex: ['ventes', 'stock'])"),
        ),
        migrations.AddField(
            model_name='agent',
            name='custom_role',
            field=models.CharField(blank=True, help_text='Titre du poste', max_length=150, null=True),
        ),
    ]
