# Generated by Django 6.0.3 on 2026-04-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_agent_allowed_modules_agent_custom_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='agent',
            table='agents',
        ),
        migrations.AlterModelTable(
            name='enterprise',
            table='entreprises',
        ),
        migrations.AlterModelTable(
            name='user',
            table='utilisateurs',
        ),
    ]
