# Generated by Django 6.0.3 on 2026-04-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_agent_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN_PME', 'Administrateur PME'), ('COMMERCANT', 'Commerçant'), ('AGENT_CAISSIER', 'Agent Caissier'), ('AGENT_DETTE', 'Agent Dette'), ('COMPTABLE', 'Comptable')], default='COMMERCANT', max_length=20),
        ),
    ]
