# Generated by Django 6.0.3 on 2026-04-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_customer_address_customer_email_supplier_address_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='achats',
        ),
        migrations.AlterModelTable(
            name='purchaseitem',
            table='articles_achat',
        ),
        migrations.AlterModelTable(
            name='sale',
            table='ventes',
        ),
        migrations.AlterModelTable(
            name='saleitem',
            table='articles_vente',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='fournisseurs',
        ),
    ]
