services:
  - type: web
    name: djagogestion-api
    env: python
    rootDir: backend_api
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn backend_api.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false # Configurer manuellement dans le tableau de bord Render
      - key: SECRET_KEY
        generateValue: true
