# Generated by Django 6.0.3 on 2026-04-02 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='users.enterprise'),
        ),
        migrations.AddField(
            model_name='debt',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='users.enterprise'),
        ),
        migrations.AddField(
            model_name='expense',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='users.enterprise'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='users.enterprise'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='users.enterprise'),
        ),
    ]
