# Generated by Django 6.0.3 on 2026-04-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receivable',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
