# Generated by Django 6.0.3 on 2026-04-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_debt_description_receivable_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='budget',
            table='budgets',
        ),
        migrations.AlterModelTable(
            name='debt',
            table='dettes',
        ),
        migrations.AlterModelTable(
            name='expense',
            table='depenses',
        ),
        migrations.AlterModelTable(
            name='receivable',
            table='creances',
        ),
        migrations.AlterModelTable(
            name='revenue',
            table='revenus',
        ),
    ]
