# Generated by Django 6.0.3 on 2026-04-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='product',
            table='produits',
        ),
        migrations.AlterModelTable(
            name='stockmovement',
            table='mouvements_stock',
        ),
    ]
